 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/calls", type: :request do
  # Call. As you add validations to Call, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Call.create! valid_attributes
      get calls_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      call = Call.create! valid_attributes
      get call_url(call)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_call_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      call = Call.create! valid_attributes
      get edit_call_url(call)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Call" do
        expect {
          post calls_url, params: { call: valid_attributes }
        }.to change(Call, :count).by(1)
      end

      it "redirects to the created call" do
        post calls_url, params: { call: valid_attributes }
        expect(response).to redirect_to(call_url(Call.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Call" do
        expect {
          post calls_url, params: { call: invalid_attributes }
        }.to change(Call, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post calls_url, params: { call: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested call" do
        call = Call.create! valid_attributes
        patch call_url(call), params: { call: new_attributes }
        call.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the call" do
        call = Call.create! valid_attributes
        patch call_url(call), params: { call: new_attributes }
        call.reload
        expect(response).to redirect_to(call_url(call))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        call = Call.create! valid_attributes
        patch call_url(call), params: { call: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested call" do
      call = Call.create! valid_attributes
      expect {
        delete call_url(call)
      }.to change(Call, :count).by(-1)
    end

    it "redirects to the calls list" do
      call = Call.create! valid_attributes
      delete call_url(call)
      expect(response).to redirect_to(calls_url)
    end
  end
end
